project_id = "ngnrmxdbzbolxroibzax"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.import-products-pdf]
verify_jwt = false

[functions.generate-banner]
verify_jwt = false
