/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as GTokenRouteImport } from './routes/g.$token'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminEventosIdRouteImport } from './routes/admin.eventos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GTokenRoute = GTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/admin/eventos',
  path: '/admin/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/admin/categorias',
  path: '/admin/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosIdRoute = AdminEventosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/eventos': typeof AdminEventosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/g/$token': typeof GTokenRoute
  '/n/$slug': typeof NSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/eventos': typeof AdminEventosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/g/$token': typeof GTokenRoute
  '/n/$slug': typeof NSlugRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/eventos': typeof AdminEventosRouteWithChildren
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/g/$token': typeof GTokenRoute
  '/n/$slug': typeof NSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/categorias'
    | '/admin/eventos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/g/$token'
    | '/n/$slug'
    | '/admin/'
    | '/painel/'
    | '/admin/eventos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/categorias'
    | '/admin/eventos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/g/$token'
    | '/n/$slug'
    | '/admin'
    | '/painel'
    | '/admin/eventos/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/categorias'
    | '/admin/eventos'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/g/$token'
    | '/n/$slug'
    | '/admin/'
    | '/painel/'
    | '/admin/eventos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminEventosRoute: typeof AdminEventosRouteWithChildren
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  GTokenRoute: typeof GTokenRoute
  NSlugRoute: typeof NSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$token': {
      id: '/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof GTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/admin/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos/$id': {
      id: '/admin/eventos/$id'
      path: '/$id'
      fullPath: '/admin/eventos/$id'
      preLoaderRoute: typeof AdminEventosIdRouteImport
      parentRoute: typeof AdminEventosRoute
    }
  }
}

interface AdminEventosRouteChildren {
  AdminEventosIdRoute: typeof AdminEventosIdRoute
}

const AdminEventosRouteChildren: AdminEventosRouteChildren = {
  AdminEventosIdRoute: AdminEventosIdRoute,
}

const AdminEventosRouteWithChildren = AdminEventosRoute._addFileChildren(
  AdminEventosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminEventosRoute: AdminEventosRouteWithChildren,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  GTokenRoute: GTokenRoute,
  NSlugRoute: NSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PainelIndexRoute: PainelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
